# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
url: "https://nobiledesigns.com" # the base hostname & protocol for your site
title: NobileDesigns
author: 
  name: NobileDesigns
  email: info@NobileDesigns.com
name: NobileDesigns
description: 
  Tech blog about SecDevOps, modern Application Development, Integration, Cloud, and Digital Transformation
baseurl: "" # the subpath of your site, e.g. /blog

# jekyll-paginate configuration
paginate: 10
timezone: America/New_York
# theme: jekyll-theme-minimal
remote_theme: jekyll/minima
sitename: NobileDesigns

# Build settings
markdown: kramdown
include: ["_pages"]
permalink: /posts/:title/
excerpt_separator: <!--more-->

include:
  - assets/css/code.css
  - assets/scripts/copy_code.js

minima:
  skin: classic

  ## date_format: "%a, %b %-d, %Y"
  date_format: "%b %-d, %Y" # "March 14, 2016" https://shopify.github.io/liquid/filters/date/
  social_links:
   - title: Jekyll repository at GitHub
     icon: linkedin
     url: "https://www.linkedin.com/company/nobiledesigns"
#    - { platform: github, user_url: "https://github.com/NobileDesigns-LLC/" }
#    - { platform: linkedin, user_url: "https://www.linkedin.com/company/nobiledesigns" }

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-last-modified-at
  - jekyll-remote-theme
  - jekyll-tagging-related_posts
  - jekyll-target-blank
  - jekyll-postfiles
  - jekyll-og-image

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json
  - npm-debug.log
  - gulpfile.js
  - sleek.png


gems:
- jekyll-last-modified-at
- "minima"


